Модуль 7 «Middleware. Валидация. Загрузка файлов»
htmlacademy-nodejs-api/buy-and-sell-6 pull request #7
Opened 2024-02-13 16:52 UTC by AntonovIgor

2024-02-17 17:48 UTC, artytrik commented on src/shared/modules/offer/dto/create-offer.messages.ts
> +    maxLength: 'Too short for field «image»',
Могу предположить, что текст тут должен начинаться с "Too long", так как мы проверяем на то, превысит ли строка определенную длину.

2024-02-17 17:59 UTC, artytrik commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @MaxLength(256, { message: CreateOfferValidationMessage.image.maxLength })
А здесь нам не нужно проверять что это строка?

2024-02-18 05:08 UTC, artytrik commented on src/shared/modules/user/dto/create-user.messages.ts
> +    invalidFormat: 'avatarPath is required',
Здесь думаю должно быть "avatarPath must be a string"

2024-02-18 05:13 UTC, artytrik commented on src/shared/modules/user/dto/create-user.messages.ts
> +    invalidFormat: 'avatarPath is required',
Или мы проверкой IsString проверяем обязательность? Прост во всех остальных строковых полях такой же текст

2024-02-18 07:47 UTC, artytrik commented on src/shared/modules/offer/dto/update-offer.messages.ts
> +export const CreateUpdateOfferMessage = {
Тут кажется надо переименовать название объекта на UpdateOfferMessage

2024-02-18 07:54 UTC, artytrik commented on src/shared/modules/comment/dto/create-comment.dto.ts
> +  @Length(5, 1024, { message: 'min is 5, max is 1024 '})
Забыл текст из объекта подставить)

2024-02-18 09:39 UTC, artytrik commented on src/shared/modules/offer/offer.controller.ts
Забыли подключить еще эту middleware в контроллер комментария. Я это к тому, что на лекции разбирался пример запроса как раз именно этого кейса (делался запрос создания комментария), но в контроллере логика комментария логика не поменялась.

2024-02-19 20:00 UTC, Dimaggio-IT requested changes

2024-02-19 20:00 UTC, Dimaggio-IT commented on package.json
>      "reflect-metadata": "0.1.13"
Также нам потребуется пакет `mime-types`. Первый поможет решить задачу с определением расширения для файла на основании MIME-типа, а вторым....

_видимо здесь так_

Также нам потребуется пакеты `mime-types` **и `nanoid`**. Первый поможет решить задачу с определением расширения для файла на основании MIME-типа, а вторым....

2024-02-20 15:24 UTC, AntonovIgor commented on package.json
>      "reflect-metadata": "0.1.13"
Спасибо! Поправим в следующем потоке. Когда-то действительно использовался nanoid. Потом отказались в пользу `randomUUID()`.

2024-02-20 15:26 UTC, AntonovIgor commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @MaxLength(256, { message: CreateOfferValidationMessage.image.maxLength })
Нет, потому что MaxLength включает проверку на строку

2024-02-20 15:30 UTC, merged